### ISSUE TITLE
Add more visible link to OrbitDB GitHub

### ISSUE THREAD

**Issue by sirfumblestone** [orbitdb/orbitdb.org#21]
After looking at https://orbitdb.org/ front page a few times now, I think it is missing a visible link to https://github.com/orbitdb. Similar to IPFS and IPFS pubsub. Today the only GH link I can find is in the GH icon at the bottom of the page. 

Do you think it would be beneficial to link the first "OrbitDB" in the first paragraph to https://orbitdb.org/?

**Comment by haadcode** [comment]
@sirfumblestone agreed :+1: A simple solution would be to link the first "OrbitDB" in the text to the repo. A slightly more involved solution would be to add widgets for GH fork/star and make very explicit that the visitor should go to Github.

Want to PR a fix with the first approach?

**Comment by sirfumblestone** [comment]
Sure. I'll make a PR :+1:
