### ISSUE TITLE
Enable analytics

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/orbitdb.org#3]
Do we want to have Google Analytics on this website? Does that send the wrong message?

**Comment by aphelionz** [comment]
I think it might - we probably want to know how people got to the website, etc but I bet there's a decentralized alternative we can find and use. It would be great if it were as "dogfoody" as possible, i.e. tracking that uses IPFS or even Orbit if possible.

Alternative to the above: no tracking but just rely on GitHub traffic insights to show how people got to GitHub from orbitdb.org and leave it at that

**Comment by shamb0t** [comment]
I don't think there's really a need to track people...do we care how they got to the website?

**Comment by shamb0t** [comment]
If so maybe an opt-in thing?

**Comment by RichardLitt** [comment]
Or we could just not use it. After all, the GitHub stats are more important, and people we meet on Gitter.

**Comment by RichardLitt** [comment]
Agreed. Let's opt out.
