### ISSUE TITLE
todomvc link points to broken demo

### ISSUE THREAD

**Issue by autonome** [orbitdb/orbitdb.org#33]
hey! i clicked through the link and the demo appears to be broken - tested in Firefox nightly, Canary and Brave nightly.

**Comment by autonome** [comment]
https://ipfs.io/ipfs/QmTJGHccriUtq3qf3bvAQUcDUHnBbHNJG2x2FYwYUecN43/

**Comment by RichardLitt** [comment]
Hmm! Not ideal. @haadcode, you wrote this originally, right? Any ideas?

**Comment by aphelionz** [comment]
It's the websocket star server (always the websocket star server :laughing:) 

We just need to update the TODO-MVC code and/or convince the libp2p team to spin it back up again for legacy purposes, nudge nudge wink wink

**Comment by aphelionz** [comment]
Putting the joke aside, the context is:

1. The primary browser transport in previous versions of libp2p was websockets. It's now Web-RTC
2. The libp2p team (mostly Protocol Labs) graciously provided a public one and warned everybody not to use it for production
3. Everybody did anyway (or did it for public demos like this one), so it goes :)
4. They deprecated the server and replaced it with the public WebRTC star server
5. After many months of warnings and deprecations, the webrtc star server was taken down

It is what it is and it's mainly just a chore to go and update the TODO-MVC code.

I might just take it off the home page in the meantime? We could link to some very impressive projects that are in production now such as [Sailplane](https://sailplane.io/), [Watchit](https://github.com/ZorrillosDev/watchit-gateway) or maybe just the awesome-orbitdb repo

**Comment by RichardLitt** [comment]
If those projects are using OrbitDB, maybe they should be in awesome-orbitdb?

**Comment by aphelionz** [comment]
Huh, Watchit is the first entry but I could have sworn Sailplane was in there. Either way Sailplane should definitely be on the home page, it rocks
