### ISSUE TITLE
Embed opencollective on website

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/orbitdb.org#38]
https://docs.opencollective.com/help/collectives/embed-contribution-flow

**Comment by RichardLitt** [comment]
I think this needs to be enabled on OC, first. 

<img width="472" alt="Screen Shot 2021-03-10 at 23 26 41" src="https://user-images.githubusercontent.com/910753/110735587-163e8280-81f8-11eb-8414-b66e743f4021.png">

**Comment by RichardLitt** [comment]
I've asked on Slack for us to be enabled.

**Comment by aphelionz** [comment]
Nice, you beat me to it on Slack :D

**Comment by RichardLitt** [comment]
I live in the OC slack.

**Comment by aphelionz** [comment]
Were we approved? :D

**Comment by RichardLitt** [comment]
Yes! But it looks bad. Design suggestions?

**Comment by aphelionz** [comment]
Hmmmm can I see a screenshot of what it looks like

**Comment by RichardLitt** [comment]
<img width="1028" alt="Screen Shot 2021-04-15 at 07 32 42" src="https://user-images.githubusercontent.com/910753/114862662-ca659700-9dbc-11eb-9092-83108f66bbcd.png">

**Comment by RichardLitt** [comment]
There's an inner scroll in there, too.

**Comment by aphelionz** [comment]
Oh jeez. Yeah let's just scrap it for now. :(

Oh well.

**Comment by RichardLitt** [comment]
We could link it, though?

**Comment by aphelionz** [comment]
Sure, yeah :)
