### ISSUE TITLE
Enable Disqus

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/orbitdb.org#8]
I am personally against enabling Disqus, but it is something to think about. I think we should keep conversation on Gitter and GitHub, and leave the blog basically as a static site without having people feel the need to check in and comment on stuff there.

**Comment by aphelionz** [comment]
I don't think we need it on orbitdb.org unless we want to show "comments" as a use case for OrbitDB and implement it in OrbitDB

**Comment by shamb0t** [comment]
Would be an awesome use-case for an orbit-diqus but agree there's no need for comments atm

**Comment by RichardLitt** [comment]
Agreed. Let's turn this off.
