### ISSUE TITLE
Add a Newsletter

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/orbitdb.org#9]
At the moment, I don't think we have one.

**Comment by RichardLitt** [comment]
Re-enable email-cta partial for this

**Comment by RichardLitt** [comment]
Got another note saying this is important. Let's add it.

**Comment by filipesmedeiros** [comment]
Hey! Do you have a platform in mind? Mailchimp?

**Comment by RichardLitt** [comment]
Unlikely to be done at this point. We don't tend to use newsletters.
